import React,{useRef,useState,useMemo} from 'react'
import {Canvas,useFrame} from '@react-three/fiber'
import {OrbitControls,ContactShadows,Clouds,Cloud,Float,Stars} from '@react-three/drei'
import * as THREE from 'three'

const COLORS=['#f9d4aa','#f5dfe4','#e8f1d4','#fff4da']
function Flower({x,z,color}){return <group position={[x,.27,z]}><mesh position={[0,.14,0]}><cylinderGeometry args={[.015,.018,.28,6]}/><meshStandardMaterial color="#5a9d79"/></mesh>{[0,1,2,3,4].map(i=><mesh key={i} position={[Math.sin(i*Math.PI*2/5)*.082,.3,Math.cos(i*Math.PI*2/5)*.082]}><sphereGeometry args={[.07,8,8]}/><meshStandardMaterial color={color}/></mesh>)}<mesh position={[0,.3,0]}><sphereGeometry args={[.045,12,12]}/><meshStandardMaterial color="#f3c763"/></mesh></group>}
function Tree({position,scale=1}){return <group position={position} scale={scale}><mesh castShadow position={[0,.65,0]}><cylinderGeometry args={[.13,.21,1.3,9]}/><meshStandardMaterial color="#957761" roughness={1}/></mesh><mesh castShadow position={[0,1.6,0]}><icosahedronGeometry args={[.91,2]}/><meshStandardMaterial color="#75b697" roughness={.92}/></mesh><mesh castShadow position={[.46,1.7,.21]}><icosahedronGeometry args={[.56,1]}/><meshStandardMaterial color="#9dd3a7" roughness={1}/></mesh></group>}
function Creature({action,onSelect}){
 const rig=useRef(),eyes=useRef(),arm=useRef(),body=useRef(),t=useRef(0)
 useFrame(({clock},dt)=>{if(!rig.current)return;t.current+=dt;const tick=clock.elapsedTime;rig.current.position.y=.34+Math.sin(tick*2.4)*.075+(action==='jump'?Math.abs(Math.sin(tick*7))*.65:0);rig.current.rotation.y= Math.sin(tick*.54)*.15; if(arm.current)arm.current.rotation.z=action==='wave'?Math.sin(tick*12)*.8-.8:Math.sin(tick*2)*.1;if(body.current)body.current.rotation.z=Math.sin(tick*1.8)*.025; if(eyes.current)eyes.current.scale.y=Math.sin(tick*.8)> .995?.12:1})
 return <group ref={rig} onClick={e=>{e.stopPropagation();onSelect()}} position={[0,.34,.5]}>
 <group ref={body}>
 <mesh castShadow position={[0,.67,0]} scale={[1.02,1.1,.92]}><sphereGeometry args={[.62,32,24]}/><meshStandardMaterial color="#ffedcc" roughness={.75}/></mesh>
 <mesh castShadow position={[0,1.33,.03]} scale={[1.17,1.03,.92]}><sphereGeometry args={[.67,32,24]}/><meshStandardMaterial color="#fff2df" roughness={.79}/></mesh>
 {[-1,1].map(s=><group key={s}><mesh castShadow position={[s*.44,1.91,-.03]} rotation={[.1,0,-s*.25]} scale={[.58,1.42,.7]}><sphereGeometry args={[.29,24,16]}/><meshStandardMaterial color="#fff2df"/></mesh><mesh position={[s*.44,1.91,.17]} rotation={[.1,0,-s*.25]} scale={[.47,1.17,.42]}><sphereGeometry args={[.26,20,16]}/><meshStandardMaterial color="#e9b9ae"/></mesh><mesh castShadow position={[s*.38,.23,.2]} scale={[1.3,.65,1.25]}><sphereGeometry args={[.24,20,12]}/><meshStandardMaterial color="#f4dfc3"/></mesh><mesh position={[s*.28,1.42,.58]} scale={[1,1,.5]}><sphereGeometry args={[.125,18,12]}/><meshStandardMaterial color="#252e32"/></mesh><mesh position={[s*.25,1.46,.655]}><sphereGeometry args={[.037,12,12]}/><meshBasicMaterial color="white"/></mesh><mesh position={[s*.47,1.19,.51]} scale={[1.5,.63,.5]}><sphereGeometry args={[.11,16,12]}/><meshStandardMaterial color="#f1bdb7" transparent opacity={.75}/></mesh></group>)}
 <group ref={eyes}/>
 <mesh position={[0,1.25,.64]} scale={[1,.65,.55]}><sphereGeometry args={[.11,18,12]}/><meshStandardMaterial color="#bb8b84"/></mesh>
 <mesh position={[0,1.13,.63]}><torusGeometry args={[.105,.022,8,22,Math.PI]}/><meshStandardMaterial color="#8a5e5b"/></mesh>
 <group ref={arm} position={[-.57,.83,0]}><mesh castShadow position={[-.09,-.13,.09]} rotation={[0,0,-.55]} scale={[.65,1.4,.8]}><sphereGeometry args={[.24,20,16]}/><meshStandardMaterial color="#ffedcc"/></mesh></group>
 <mesh castShadow position={[.64,.71,.05]} rotation={[0,0,-.7]} scale={[.62,1.22,.8]}><sphereGeometry args={[.24,20,16]}/><meshStandardMaterial color="#ffedcc"/></mesh>
 </group>
 </group>
}
function Land(){const flowers=useMemo(()=>Array.from({length:36},(_,i)=>{let a=i*2.39996,r=2.55+(i%6)*.42;return {x:Math.cos(a)*r,z:Math.sin(a)*r,color:COLORS[i%COLORS.length]}}),[]);return <group><mesh receiveShadow position={[0,-.48,0]}><cylinderGeometry args={[5.65,5.12,1.25,72]}/><meshStandardMaterial color="#bd9b78" roughness={1}/></mesh><mesh receiveShadow position={[0,.02,0]}><cylinderGeometry args={[5.78,5.65,.29,72]}/><meshStandardMaterial color="#8ec9a1" roughness={1}/></mesh><mesh receiveShadow position={[0,.19,.45]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[2.15,64]}/><meshStandardMaterial color="#d8cba8" roughness={1}/></mesh>{[[4.2,2.2,.9],[-4,-.6,.95],[3,-3.5,.73],[-2.9,3.5,.76]].map(([x,z,s],i)=><Tree key={i} position={[x,.18,z]} scale={s}/>)}{flowers.map((f,i)=><Flower key={i} {...f}/>)}{Array.from({length:24},(_,i)=>{const a=i*2.4;let r=4.6+(i%3)*.15;return <mesh key={i} position={[Math.cos(a)*r,.24,Math.sin(a)*r]} scale={[.58,.34,.52]} castShadow><icosahedronGeometry args={[1,1]}/><meshStandardMaterial color={i%3===0?'#83b991':'#a0ce9b'}/></mesh>})}</group>}
export default function World({action,onSelect}){return <Canvas shadows dpr={[1,1.8]} camera={{position:[5.9,4.5,9.5],fov:39}} gl={{antialias:true}}><color attach="background" args={['#badfdb']}/><fog attach="fog" args={['#badfdb',16,31]}/><ambientLight intensity={1.45}/><hemisphereLight intensity={1.25} color="#effff6" groundColor="#83ad99"/><directionalLight castShadow position={[-5,9,5]} intensity={2.35} color="#fff2d9" shadow-mapSize={[1024,1024]} shadow-camera-left={-9} shadow-camera-right={9} shadow-camera-top={9} shadow-camera-bottom={-9}/><Float speed={.9} floatIntensity={.12} rotationIntensity={0}><mesh position={[-8,6,-7]}><sphereGeometry args={[1.6,24,16]}/><meshBasicMaterial color="#fff7e7"/></mesh></Float><Land/><Creature action={action} onSelect={onSelect}/><ContactShadows opacity={.22} scale={7} blur={2} far={3} position={[0,.17,.5]}/><OrbitControls enablePan={false} minPolarAngle={.7} maxPolarAngle={1.34} minDistance={6} maxDistance={14} target={[0,1,0]} enableDamping dampingFactor={.08}/></Canvas>}