import React,{useMemo,useRef} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {MapControls,ContactShadows} from '@react-three/drei';
import * as THREE from 'three';
const greens=['#7fb89d','#91c7a5','#aecfa8','#6da98f'];
function Tree({position,scale=1,tint=0}){return <group position={position} scale={scale}><mesh castShadow position={[0,.57,0]}><cylinderGeometry args={[.14,.2,1.14,8]}/><meshStandardMaterial color="#a88c70"/></mesh><mesh castShadow position={[0,1.36,0]}><icosahedronGeometry args={[.88,1]}/><meshStandardMaterial color={greens[tint%4]} roughness={.9}/></mesh><mesh castShadow position={[.35,1.45,.2]}><icosahedronGeometry args={[.58,1]}/><meshStandardMaterial color={greens[(tint+1)%4]}/></mesh></group>}
function Bush({position,scale=1}){return <mesh castShadow position={position} scale={[scale*1.2,scale*.6,scale]}><icosahedronGeometry args={[.54,1]}/><meshStandardMaterial color="#7eb998" roughness={1}/></mesh>}
function Flower({position,color}){return <group position={position}><mesh position={[0,.12,0]}><cylinderGeometry args={[.014,.014,.24,5]}/><meshStandardMaterial color="#438b68"/></mesh>{[0,1,2,3,4].map(i=><mesh key={i} position={[Math.sin(i*1.256)*.07,.25,Math.cos(i*1.256)*.07]}><sphereGeometry args={[.056,8,8]}/><meshStandardMaterial color={color}/></mesh>)}<mesh position={[0,.25,0]}><sphereGeometry args={[.043,8,8]}/><meshStandardMaterial color="#f2c76d"/></mesh></group>}
function Naverio({mood,onClick}){const ref=useRef(),ear=useRef();useFrame(({clock})=>{let t=clock.elapsedTime;if(!ref.current)return;ref.current.position.y=.28+Math.sin(t*2)*.045+(mood==='play'?Math.abs(Math.sin(t*6))*.3:0);ref.current.rotation.y=Math.sin(t*.3)*.16;if(ear.current)ear.current.rotation.z=Math.sin(t*2)*.04});return <group ref={ref} position={[0,.28,0]} onClick={e=>{e.stopPropagation();onClick()}}><group ref={ear}><mesh castShadow position={[0,.66,0]} scale={[.8,.86,.73]}><sphereGeometry args={[.65,32,24]}/><meshStandardMaterial color="#f1dec5" roughness={.88}/></mesh><mesh castShadow position={[0,1.2,.025]} scale={[1,.88,.8]}><sphereGeometry args={[.68,32,24]}/><meshStandardMaterial color="#fff0d8" roughness={.86}/></mesh>{[-1,1].map(s=><group key={s}><mesh castShadow position={[s*.47,1.79,-.04]} rotation={[0,0,-s*.22]} scale={[.8,1.35,.72]}><sphereGeometry args={[.26,20,16]}/><meshStandardMaterial color="#fff0d8"/></mesh><mesh position={[s*.47,1.79,.15]} rotation={[0,0,-s*.22]} scale={[.6,1,.46]}><sphereGeometry args={[.24,20,16]}/><meshStandardMaterial color="#e7aea6"/></mesh><mesh position={[s*.27,1.22,.55]} scale={[1,1,.6]}><sphereGeometry args={[.105,20,16]}/><meshStandardMaterial color="#343b3e"/></mesh><mesh position={[s*.25,1.26,.62]}><sphereGeometry args={[.03,12,8]}/><meshBasicMaterial color="#fff"/></mesh><mesh position={[s*.42,1.03,.5]} scale={[1,.6,.5]}><sphereGeometry args={[.1,16,12]}/><meshStandardMaterial color="#efb4ad"/></mesh><mesh castShadow position={[s*.42,.24,.18]} scale={[1.2,.6,1.1]}><sphereGeometry args={[.24,16,12]}/><meshStandardMaterial color="#e9d4ba"/></mesh></group>)}<mesh position={[0,1.07,.607]}><sphereGeometry args={[.09,16,12]}/><meshStandardMaterial color="#bc8b81"/></mesh><mesh position={[0,.98,.6]}><torusGeometry args={[.085,.016,8,18,Math.PI]}/><meshStandardMaterial color="#93645c"/></mesh></group></group>}
function Landscape(){const scene=useMemo(()=>{let trees=[],flowers=[],bushes=[];for(let i=0;i<33;i++){const a=i*2.399,r=4.4+(i%7)*1.32;trees.push({x:Math.cos(a)*r,z:Math.sin(a)*r,scale:.7+(i%5)*.13,tint:i})}for(let i=0;i<90;i++){let a=i*2.4,r=2.8+(i%17)*.66;flowers.push({x:Math.cos(a)*r,z:Math.sin(a)*r,c:i%3===0?'#f6dbb8':i%3===1?'#e6b7b4':'#f5edd9'})}for(let i=0;i<42;i++){let a=i*2.36,r=3.7+(i%11)*1.16;bushes.push({x:Math.sin(a)*r,z:Math.cos(a)*r})}return {trees,flowers,bushes}},[]);return <group><mesh receiveShadow position={[0,-.42,0]}><cylinderGeometry args={[14.3,14.1,1,96]}/><meshStandardMaterial color="#b0a085" roughness={1}/></mesh><mesh receiveShadow position={[0,.04,0]}><cylinderGeometry args={[14.4,14.3,.22,96]}/><meshStandardMaterial color="#a3cbb1" roughness={1}/></mesh><mesh receiveShadow rotation={[-Math.PI/2,0,0]} position={[0,.16,0]}><circleGeometry args={[2.7,48]}/><meshStandardMaterial color="#d6c6a7" roughness={1}/></mesh>{scene.trees.map((v,i)=><Tree key={i} position={[v.x,.16,v.z]} scale={v.scale} tint={v.tint}/>)}{scene.flowers.map((v,i)=><Flower key={i} position={[v.x,.16,v.z]} color={v.c}/>)}{scene.bushes.map((v,i)=><Bush key={i} position={[v.x,.42,v.z]} scale={.7+(i%4)*.14}/>)}</group>}
export default function World({mood,onCharacterClick}){return <Canvas shadows camera={{position:[7.5,9.5,14],fov:35,near:.1,far:90}} dpr={[1,1.7]} gl={{antialias:true}}><color attach="background" args={['#b9dad7']}/><fog attach="fog" args={['#b9dad7',24,64]}/><ambientLight intensity={1.7}/><hemisphereLight intensity={.8} color="#f3f7eb" groundColor="#8bb299"/><directionalLight castShadow position={[-7,12,7]} intensity={2} color="#fff2db" shadow-mapSize={[1024,1024]} shadow-camera-left={-17} shadow-camera-right={17} shadow-camera-top={17} shadow-camera-bottom={-17}/><Landscape/><Naverio mood={mood} onClick={onCharacterClick}/><ContactShadows position={[0,.16,0]} opacity={.16} scale={7} blur={2.8}/><MapControls makeDefault enableRotate={false} enableZoom={false} enablePan={true} screenSpacePanning={true} panSpeed={.85} enableDamping dampingFactor={.08} minPolarAngle={.8} maxPolarAngle={.8} target={[0,0,0]}/></Canvas>}